// Generated by CoffeeScript 1.8.0
(function() {
  var moment, net, portNumber, server;

  moment = require('moment');

  net = require('net');

  portNumber = process.argv[2];

  server = net.createServer(function(socket) {
    var now;
    now = moment().format('YYYY-MM-DD hh:mm');
    socket.write("" + now + "\n");
    return socket.end();
  });

  server.listen(portNumber);

}).call(this);
