// Generated by CoffeeScript 1.8.0
(function() {
  var fs, http, path, portNumber, server;

  portNumber = process.argv[2];

  path = process.argv[3];

  fs = require('fs');

  http = require('http');

  server = http.createServer(function(request, response) {
    var fileStream;
    fileStream = fs.createReadStream(path);
    return fileStream.pipe(response);
  });

  server.listen(portNumber);

}).call(this);
