// Generated by CoffeeScript 1.8.0
(function() {
  var callback, fs, path;

  callback = function(err, buffer) {
    var contents, lines, newlines;
    if (err) {
      return console.log(err);
    } else {
      contents = buffer.toString();
      lines = contents.split('\n');
      newlines = lines.length - 1;
      return console.log(newlines);
    }
  };

  fs = require('fs');

  path = process.argv[2];

  fs.readFile(path, callback);

}).call(this);
