// Generated by CoffeeScript 1.8.0
(function() {
  var directory, extension, fs, path;

  fs = require('fs');

  path = require('path');

  directory = process.argv[2];

  extension = process.argv[3];

  fs.readdir(directory, function(err, files) {
    var file, _i, _len, _results;
    if (err) {
      return console.log(err);
    } else {
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if (path.extname(file) === ("." + extension)) {
          _results.push(console.log(file));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  });

}).call(this);
