// Generated by CoffeeScript 1.8.0
(function() {
  var callback, directory, extension, p6Module;

  directory = process.argv[2];

  extension = process.argv[3];

  p6Module = require('./p6Module.js');

  callback = (function(_this) {
    return function(err, files) {
      var file, _i, _len, _results;
      if (err) {
        return console.log(err);
      } else {
        _results = [];
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          _results.push(console.log(file));
        }
        return _results;
      }
    };
  })(this);

  p6Module(directory, extension, callback);

}).call(this);
