// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(directory, extension, callback) {
    var fs, path;
    fs = require('fs');
    path = require('path');
    return fs.readdir(directory, function(err, files) {
      var file, retval, _i, _len;
      if (err) {
        return callback(err);
      } else {
        retval = [];
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          if (path.extname(file) === ("." + extension)) {
            retval.push(file);
          }
        }
        return callback(null, retval);
      }
    });
  };

}).call(this);
