// Generated by CoffeeScript 1.8.0
(function() {
  var http, url;

  url = process.argv[2];

  http = require('http');

  http.get(url, function(response) {
    return response.on('data', function(data) {
      return console.log(data.toString());
    });
  });

}).call(this);
