// Generated by CoffeeScript 1.8.0
(function() {
  var callback, concat, http, url;

  url = process.argv[2];

  http = require('http');

  concat = require('concat-stream');

  callback = function(data) {
    var string;
    string = data.toString();
    console.log(string.length);
    return console.log(string);
  };

  http.get(url, function(response) {
    return response.pipe(concat(callback));
  });

}).call(this);
