// Generated by CoffeeScript 1.8.0
(function() {
  var concat, http, urls;

  urls = process.argv;

  http = require('http');

  concat = require('concat-stream');

  urls = urls.slice(2);

  http.get(urls[0], function(response) {
    return response.pipe(concat(function(data) {
      var string;
      string = data.toString();
      console.log(string);
      return http.get(urls[1], function(response) {
        return response.pipe(concat(function(data) {
          string = data.toString();
          console.log(string);
          return http.get(urls[2], function(response) {
            return response.pipe(concat(function(data) {
              string = data.toString();
              return console.log(string);
            }));
          });
        }));
      });
    }));
  });

}).call(this);
